### ISSUE TITLE
Missing newline in shell message after not finding member

### ISSUE THREAD

**Issue by jleeothon** [Seldomberry/Cortex#133]
In file Fast_MemberExpr.c:38:
```
Fast_Parser_error(yparser(), "unresolved member '%s' for type '%s'", member, cx_fullname(type, id));
```

**Comment by jleeothon** [comment]
I noticed this error occurs in more than one error message. @SanderMertens should these error messages provide a newline themselves or is it addressed upper in the stack?

**Comment by SanderMertens** [comment]
These issues occur due to a recent change in how error messages are processed. Once my branch is synchronized with master the issue should disappear.

In general, error messages do not provide their own newline. Reason for this is so that they can be embedded in other messages.
