### ISSUE TITLE
Missing core and C binding snippets related to cx_iterator

### ISSUE THREAD

**Issue by jleeothon** [Seldomberry/cortex#143]
There were missing pieces of code so that iterators fully exist as a core class.

For example:
```
// cx__type.h
+#define cx_iterator(t) ((cx_iterator)t)
```

```
// cx__meta.h
CX_META_OBJECT(class, iterator);
```

Also, pieces of code that generate dependencies.

**Comment by SanderMertens** [comment]
Could you describe what this issue is about?

**Comment by jleeothon** [comment]
Made a small edit in description. This was a basically a place to associate information to the said commit. This changes were long made and some might have been superseded by the new iteration approach. We could close this.
