### ISSUE TITLE
Handling buffer size for string escaping

### ISSUE THREAD

**Issue by jleeothon** [Seldomberry/Cortex#88]
How should we handle allocation of the right size for a buffer to feed into `stresc`?

In a **first approach**, if we make a signature similar to `snprintf`, we still don't get any info about size a priori. Throwing in a magic big number seems unacceptable. For performance/memory purposes, we may want to specify a maximum limit, but unlike `snprintf`, I would also like to accept zero as a "do what you want".

A **second approach** is to handle the buffer allocation inside the string; that requires receiving a double pointer. Something like:
`char *mystresc(const char *in, char **out)`
To know the size, we would need to e.g. do pointer arithmetics. Internally we'll need something that checks the necessary size.

Example usage:

```
char hel__lo = "he\t\tllo";
char *buffer;
stresc(he__llo, &buffer);
```

A **third approach** is to provide a helper function something like:
`size_t stresclen(const char *in)`
It provides information a priori. I wonder if the above approach is more desirable because it wraps around this complexity (maybe unneeded), but I like this one better.

Example usage:

```
char hel__lo = "he\t\tllo";
char *buffer  = db_malloc(stresclen(he__llo));
stresc(he__llo, buffer);
```

A **fourth approach** can be to combine the 1st and 3rd ones, in a signature like:
```
size_t stresclen(const char *in);
char *stresc(const char *in, char *out, size_t n);
// --- example usage
char hel__lo = "he\t\tllo";
char *buffer = db_malloc(stresclen(hel__llo));
stresc(he__llo, buffer, 0);
```
Where `n` the is the maximum number of bytes to write including the null character, or zero to attempt to write everything.

**Comment by SanderMertens** [comment]
After discussion we agreed that approach 1 is favorable. The separate length function is now merged with the string escape function. The signature has been made to look more like snprintf, and the behavior is the same with regards to memory usage and reporting on number of written characters. Like snprintf, the new function will also accept passing a 0.
