### ISSUE TITLE
Typedef must go

### ISSUE THREAD

**Issue by SanderMertens** [Seldomberry/cortex#92]
The usage of typedefs has proven to be of very limited value. Because the typesystem allows for easy creation of own primitive / collection types type aliasing is not really required. Aliasing interface types like structs and classes is too rare to justify the feature.

**Comment by jleeothon** [comment]
Side question, is there native support for overriding cast operations?

**Comment by SanderMertens** [comment]
No. Cast operations are currently hard coded in the type system. Casts between primitive types are performed by the cx_convert routine. The cx_type_castable function determines whether types can cast.

Composite types can only cast to each other when there is an inheritance relation. A sub class can always be assigned without casts to a base. The reverse (base to a subclass) requires an explicit cast.

The array, sequence and list collection types can be casted to each other provided they share compatible element types. Restrictions apply to array: since it is of fixed length sequence/list cannot be casted to an array where the reverse is possible.

**Comment by SanderMertens** [comment]
![screen shot 2015-01-25 at 3 28 01 pm](https://cloud.githubusercontent.com/assets/9919222/5893147/e9a20cfe-a4a6-11e4-971f-0ce54161b37c.png)
